services:
  db:
    image: mariadb:11.3.2
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 10
    ports:
      - "0.0.0.0:3307:3306"
    environment:
      MARIADB_USER: limble-test
      MARIADB_PASSWORD: limble-test-password
      MARIADB_DATABASE: limble
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: 1

  migrate:
    image: mariadb:11.3.2
    command: ["/code/build-schema.sh"]
    volumes:
      - "./schema:/code"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: limble-test
      DATABASE_PASSWORD: limble-test-password
      DATABASE_NAME: limble
    depends_on:
      db:
        condition: service_healthy

  server:
    image: node:21.7.1-bookworm-slim
    command: ["npm", "start"]
    working_dir: /code
    user: node
    volumes:
      - "./server/:/code"
    ports:
      - "0.0.0.0:3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: limble-test
      DATABASE_PASSWORD: limble-test-password
      DATABASE_NAME: limble
    depends_on:
      db:
        condition: service_healthy
